### ISSUE TITLE
请问easypanel下怎么配置，可以给详细点的教程吗？

### ISSUE THREAD

**Issue by kentcc88** [zlkbdotnet/zfaka#10]
请问easypanel下怎么配置，可以给详细点的教程吗？尝试配置之后，发现404错误，就是跳转到install目录的时候出现404，不知道如何解决，其他的按nginx教程上说的，该修改的修改了。

**Comment by zlkbdotnet** [comment]
加群交流吧，很多高手群友

**Comment by kentcc88** [comment]
我加入群了呢，不过里面没多杀人哈？另外我想问问，docker镜像我试了，但mysql似乎有点问题？安装时总是提示“失败:SQLSTATE[HY000] [2002] Connection refused”
[](url)
