### ISSUE TITLE
BUG反馈：添加Sendgrid邮箱的问题

### ISSUE THREAD

**Issue by pinkpand** [zlkbdotnet/zfaka#111]
zfaka发信邮箱设置的第一项“邮箱账号”，只能以xxx@xxx.xxx的邮箱格式填写，所以导致误以为“邮箱账号”就是邮箱，测试多次无效。其实“邮箱账号”在sendgrid中就是登陆用户名，而用户名大部分只是一个英文单词，并不是邮箱格式。所以我不得不把我的用户名更改成一个xxx@xxx.xxx的邮箱格式，才可以在zfaka中使用。但是对于一些不能更改用户名的 邮件服务商 可能就没有办法了。也可能我这只是碰巧，我就这么一说，您就这么一看。

**Comment by zlkbdotnet** [comment]
感谢反馈 ，我去处理一下
