### ISSUE TITLE
后台设置中除第一页其他数据无法加载

### ISSUE THREAD

**Issue by x1184** [zlkbdotnet/zfaka#12]
![qq 20181112003930](https://user-images.githubusercontent.com/24709674/48315648-cb0a0a00-e613-11e8-9148-613b55f26b74.png)

如图 直接第二页数据无法加载  但是第一页是正常的 第三页也不正常

**Comment by zlkbdotnet** [comment]
打开数据库，检查配置项的value，不允许回车。换行

**Comment by zlkbdotnet** [comment]
新版已经支持一键修复，请更新最新版

**Comment by x1184** [comment]
好的 测试生效 感谢
