### ISSUE TITLE
个人没有商家收款咋办

### ISSUE THREAD

**Issue by zyh13146** [zlkbdotnet/zfaka#121]
个人没有企业营业执照，怎么收款啊

**Comment by yuhan5187** [comment]
用收款宝啊，作者的，我在用

**Comment by zyh13146** [comment]
支付宝微信支持吗，手续费多少。

**Comment by yuhan5187** [comment]
支持啊，我买了，就是一个月有限额，超过限额要购买流量包

zyh13146 <notifications@github.com> 于 2019年7月28日周日 08:03写道：
