### ISSUE TITLE
宝塔面板 php7.2 编译 yaf 出错 error: ‘ZEND_ACC_CLONE’ 

### ISSUE THREAD

**Issue by zen4lcc** [zlkbdotnet/zfaka#13]
宝塔面板 php7.2 编译 yaf 出错 error: ‘ZEND_ACC_CLONE’ 

😓

**Comment by zlkbdotnet** [comment]
php7.2编译yaf不存在任何问题，安装时注意一下yaf版本即可。 由于不存在什么问题，如果你是技术控，折腾党建议自己再多折腾一下，否则建议你用宝塔的自带php7.1
