### ISSUE TITLE
无能为力了，重装之后首页报错500

### ISSUE THREAD

**Issue by 5wszxt** [zlkbdotnet/zfaka#14]
换了服务器直接配置的环境，
先是php7.1，和以前的服务器一样配置之后首页打不开，但是ico图标ok
未配置yaf会报错，这个看得出来，但是配置重启之后报500就尴尬了

然后再安装7.2，按教程修改了php的位置安装yaf，一样的500
唉，都是修改了配置文件的，，，

你试试这个？http://f.dwza.cc/favicon.ico

**Comment by zlkbdotnet** [comment]
不用试了。，肯定是你的问题

三条路给你

1.放弃本项目
2.发挥自己的主观能动性，认真仔细的阅读wiki
3.加本项目QQ群，群友提供免费和收费协助

**Comment by 5wszxt** [comment]
> 不用试了。，肯定是你的问题
> 
> 三条路给你
> 
> 1.放弃本项目
> 2.发挥自己的主观能动性，认真仔细的阅读wiki
> 3.加本项目QQ群，群友提供免费和收费协助

诶，我也知道是我的问题，但还没找到。。。

**Comment by qiudong19901008** [comment]
你重新下载源代码然后解压重装, 这样就能搞定.
因为zfaka的index.php是安装引导, 如果你安装了一遍, 再运行该引导就会500错误.
