### ISSUE TITLE
发现一个漏洞

### ISSUE THREAD

**Issue by 984231098** [zlkbdotnet/zfaka#160]

**Comment by 984231098** [comment]
由于涉及到安全问题，暂不公布详情，还请作者私聊我，测试版本是v1.4.0，新版不知道有没有

**Comment by zlkbdotnet** [comment]
> 由于涉及到安全问题，暂不公布详情，还请作者私聊我，测试版本是v1.4.0，新版不知道有没有

直接反馈给我吧,我现在抽空修复一下
