### ISSUE TITLE
能请教下如何配置支付宝当面付吗？

### ISSUE THREAD

**Issue by xiaofq** [zlkbdotnet/zfaka#18]
app_id
ali_public_key
rsa_private_key
只有这三个参数欸，我填了支付提示错误，
但我用过sspanel面板的当面付可以搞定，它的是要填以下参数即可：
['f2fpay_app_id']='2017221985';
['f2fpay_p_id']='20887023';
['alipay_public_key']='MIIBxxxxxxxxxxxxxx';
['merchant_private_key']='MIIExxxxxxxxxxxxxxxxxxx';

但是zfaka少了签约管理里合作伙伴身份PID也就是 ['f2fpay_p_id']，所以想问问这怎么搞呢，谢谢

sspanel的支付填写方式链接： https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki/%E6%94%AF%E4%BB%98%E7%B3%BB%E7%BB%9F%E5%AF%B9%E6%8E%A5%E6%95%99%E7%A8%8B

**Comment by zlkbdotnet** [comment]
我怎么感觉你的支付宝当面付,和我们大家的支付宝当面付不一样...

所以无法帮到你了,建议你再百度一下

**Comment by xiaofq** [comment]
> 我怎么感觉你的支付宝当面付,和我们大家的支付宝当面付不一样...
> 
> 所以无法帮到你了,建议你再百度一下

这……，那zfaka的rsa_private_key填的具体是啥呢，当面付应用里面的回调地址是不是也要填一下呢。😅
