### ISSUE TITLE
1.0.7功能需求征集

### ISSUE THREAD

**Issue by zlkbdotnet** [zlkbdotnet/zfaka#2]
请留下您的需求吧。

**Comment by isjing2** [comment]
![image](https://user-images.githubusercontent.com/40830740/42720264-a6555dde-8756-11e8-99e0-e932ecd57a00.png)
建议加个商品分类，

**Comment by a2313153** [comment]
建议写个商品单链接伪静态默认的太长了

**Comment by a2313153** [comment]
希望加入总收入和每日收入统计、订单数，总订单数，如果是曲线图就哥更赞

**Comment by yecsama** [comment]
1.加一个产品单链接
2.加一个统计功能，今日订单，总订单，今日收入，总收入。可以把统计设置成按时间查询的，默认当天的订单。
3.商品管理，可以在列表指点操作上下架，增加一个已卖出，把数量改为 库存卡。
4.页面整体加宽一些（1366px），能更直观的显示一些数据。
5....

**Comment by ticifer** [comment]
订单查询重复查询显示，商品选择需改善；相关图和情况已经Q发过给你

**Comment by ticifer** [comment]
已更新，订单查询重复测试已处理；商品选择那条空白框依旧存在，麻烦修修或告知该处修改方法，修修

**Comment by ticifer** [comment]
上述问题测试已处理，感谢；建议能在提交订单的时候多个备注栏，以便下单提交一些自定义信息或备注

**Comment by wrrong** [comment]
希望验证码和密码功能能在后天打开或关闭

**Comment by wrrong** [comment]
还有不强迫留邮箱，很多人不喜欢留邮箱

**Comment by a2313153** [comment]
查询页和登陆页的验证码开关可以有

**Comment by wrrong** [comment]
支付金额，码支付动态会+0.01，如果别人不知道，支付的还是0.1而不是0.11的话，订单会乱

**Comment by a2313153** [comment]
这时候你需要在码支付那添加各个金额的0.1至0.2，如果你每天订单量很多就再多添加0.3至更多，添加后，遇到增加的他会自动为增加的哪个二维码
http://ww1.sinaimg.cn/large/5fd2b030gy1fu3hy3q9xoj20ao0bzq3d.jpg

**Comment by a2313153** [comment]
http://ww1.sinaimg.cn/large/5fd2b030gy1fu3hz4ujk2j20oh0exjsn.jpg
如图

**Comment by byxiaopeng** [comment]
limit_email_order设置成0  依旧提示    处理失败,商品限制重复下单,请直接查询订单进行支付

**Comment by lonelymoonlight** [comment]
强烈要求 修改下码支付，动态金额导致丢单

**Comment by ticifer** [comment]
![_20180903084802](https://user-images.githubusercontent.com/22905619/44962665-1b9b2200-af56-11e8-8490-f61ffc6e172a.png)
建议增加一栏备注或留言，用于手工发卡所需的备注信息等，谢谢。

**Comment by zlkbdotnet** [comment]
1.0.7已更新，关闭此贴；
