### ISSUE TITLE
手工发货后二次邮件模板

### ISSUE THREAD

**Issue by Gakki-smile** [zlkbdotnet/zfaka#219]

**Comment by Gakki-smile** [comment]
手工发货之后在几分钟内会再给客户发送一封邮件，请问这个模板在哪里修改？

**Comment by coderykw** [comment]
你就这里搜那个模板的关键字

**Comment by zlkbdotnet** [comment]
![image](https://user-images.githubusercontent.com/14122670/120727976-764e7780-c50e-11eb-85c6-e53bb8cd092e.png)
