### ISSUE TITLE
订单号含有下划线，短线不能查询的问题

### ISSUE THREAD

**Issue by jeeinn** [zlkbdotnet/zfaka#22]
目前程序是订单号**查询时**只能为英文和数字，当订单号设置前缀含有下划线、中间短线时会在查询时被过滤。

* 希望可以考虑在过滤函数中放行，如
`application/library/Safe/MyString.php`

* 或者在后台订单前缀配置项做提醒：`前缀只能为英文`

**Comment by zlkbdotnet** [comment]
说实话,从来没想过订单前缀会设置特殊符号;

感谢你的提醒,目前已经在后台订单前缀配置项做了对应提醒
