### ISSUE TITLE
码支付api接口变了

### ISSUE THREAD

**Issue by hofaeair** [zlkbdotnet/zfaka#222]
接口地址：http://api5.xiuxiu888.com/creat_order/
api文档：https://qr.kjkl8.com/apiword/r1YwqrOte.html
新的官网：https://qr.kjkl8.com/home.html
不知道为什么忽然变了，前几天旧的官网还能访问。

**Comment by zlkbdotnet** [comment]
第三方支付接口可以自行对接，我懒的处理了
