### ISSUE TITLE
发送邮件怎么设置

### ISSUE THREAD

**Issue by zxmlysxl** [zlkbdotnet/zfaka#25]
您好，我在后台邮箱设置里的邮箱地址和发件人邮箱设置为同一个地址，是139邮箱的，邮箱密码及发件服务器和端口也填 了，但消息队列中邮件都是待发送状态，试过换腾讯企业邮箱也是同样的情况，请问是我还有哪里没设置好吗，谢谢

**Comment by zxmlysxl** [comment]
加了，而且宝塔定时任务每5分钟就有日志输出：
----------------------------------------------------------------------------
★[2019-01-07 08:30:01] Successful
----------------------------------------------------------------------------
----------------------------------------------------------------------------
★[2019-01-07 08:35:01] Successful
----------------------------------------------------------------------------
----------------------------------------------------------------------------
★[2019-01-07 08:40:02] Successful
----------------------------------------------------------------------------

**Comment by zxmlysxl** [comment]
刚刚把5.6的php卸载后改用单php定时任务能正常发送了，一会儿我再测试下多php看还正常吗

**Comment by zlkbdotnet** [comment]
多ＰＨＰ环境下，自己仔细看ＷＩＫＩ吧，ＷＩＫＩ中有相关说明
