### ISSUE TITLE
用户注册邮箱地址被截断

### ISSUE THREAD

**Issue by zxmlysxl** [zlkbdotnet/zfaka#27]
您好，刚刚测试普通用户注册，我注册时填的邮箱地址是zxmlysxl@139.com，注册成功后我登录到我的资料页查看却发现邮箱地址被截断，变成zysxl@139.com，我试过用其他邮箱注册发现系统会自动删除"xml"字符串

**Comment by zlkbdotnet** [comment]
感谢反馈，已经处理
