### ISSUE TITLE
邮件队列突然显示处理失败

### ISSUE THREAD

**Issue by hyjsos** [zlkbdotnet/zfaka#28]
如图。系统是centos7.5，宝塔5.8.8面板，单一PHP7.1，faka版本是1.3.6.宝塔定时任务也是OK的。邮箱的smtp测试也是没有问题的，不知道大佬有没啥经验，或者有啥排查方法没。
![123](https://user-images.githubusercontent.com/34772779/51022422-224e3b80-15bf-11e9-8dbb-54393ac1296f.jpg)

**Comment by zlkbdotnet** [comment]
处理失败的话，您可以登录数据库，查看t_email_queue表的sendresult字段，这里记录了失败的具体原因

**Comment by zlkbdotnet** [comment]
你也可以等待 1.3.7版本,会在这里增加错误提示

**Comment by zlkbdotnet** [comment]
1.3.7已经发布
