### ISSUE TITLE
从1.3.5换到1.3.6后新增商品显示新增失败

### ISSUE THREAD

**Issue by amoshere** [zlkbdotnet/zfaka#30]
全新安装1.3.6还是这样。请问是哪个方面有问题？
服务器 使用的Azure
系统为 Debian9
Nginx 版本1.8
PHP7.2
mysql 5.7

换回1.3.5后可以新增商品了

**Comment by zlkbdotnet** [comment]
我测试了好几次,貌似都没这样的情况

**Comment by amoshere** [comment]
> 我测试了好几次,貌似都没这样的情况

...我也不知道问题在哪，我试过全新安装，和后台升级，到了3.6就是不能新增
我在log里找到下面这个

`SQL: INSERT INTO t_products (`typeid`,`name`,`password`,`description`,`stockcontrol`,`qty`,`price`,`auto`,`addons`,`active`,`sort_num`,`addtime`) VALUES ('1','皮皮虾我们走','','测试','1','0','1','1','','1','99','1547278999')
Error: Field 'imgurl' doesn't have a default value
LINE__________FUNCTION__________FILE______________________________________
558________checkResult__________/www/wwwroot/zfaka/application/library/Core/Model.php
349________Execute______________/www/wwwroot/zfaka/application/library/Core/Model.php
255________Insert_______________/www/wwwroot/zfaka/application/modules/Admin/controllers/Products.php
___________editajaxAction_______
7__________run__________________/www/wwwroot/zfaka/public/index.php`

**Comment by zlkbdotnet** [comment]
感谢,这个问题,在WIKI中,其实我很早就有提到过https://zlkb.net/302.html

当然,这个问题会在接下来的1.3.7中进行处理

**Comment by amoshere** [comment]
> 感谢,这个问题,在WIKI中,其实我很早就有提到过https://zlkb.net/302.html
> 
> 当然,这个问题会在接下来的1.3.7中进行处理

嗯嗯，麻烦了。我去试试
