### ISSUE TITLE
请问邮件发送是用什么发送的?

### ISSUE THREAD

**Issue by dgfun** [zlkbdotnet/zfaka#32]
用的是收款宝，微信支付
试了下订单能正常完成，
但邮件是待发送，失败原因为空，用的是阿里企业邮
同一台VPS上的博客，使用插件，可以自动发邮件
还有个问题，回调地址我看两边的后台都没地方填，是不用填吗

运行环境为debian9+mysql5.7+nginx1.14+php7.2
目前只在cron这里看到错误，但是不是不需要自建邮件服务器吗？

Jan 20 23:54:01  CRON[5207]: (CRON) info (No MTA installed, discarding output)
Jan 20 23:54:01  CRON[5207]: pam_unix(cron:session): session closed for user root
Jan 20 23:56:01  pam_unix(cron:session): session opened for user root by (uid=0)
Jan 20 23:56:01  CRON[5274]: (root) CMD (php -q /data/wwwroot/zfaka/public/cli.php request_uri="/crontab/sendemail/index" )
Jan 20 23:56:01  CRON[5273]: (CRON) info (No MTA installed, discarding output)
Jan 20 23:56:01  CRON[5273]: pam_unix(cron:session): session closed for user root
Jan 20 23:58:01  CRON[5276]: pam_unix(cron:session): session opened for user root by (uid=0)
Jan 20 23:58:01  CRON[5277]: (root) CMD (php -q /data/wwwroot/zfaka/public/cli.php request_uri="/crontab/sendemail/index" )
Jan 20 23:58:01  CRON[5276]: (CRON) info (No MTA installed, discarding output)
Jan 20 23:58:01  CRON[5276]: pam_unix(cron:session): session closed for user root

**Comment by zlkbdotnet** [comment]
1.发送邮件用的smtp模式，也就是使用第三方邮箱系统；不需要自建；
2.正常发送邮件需要配置定时计划，请仔细看wiki说明

**Comment by dgfun** [comment]
> 1.发送邮件用的smtp模式，也就是使用第三方邮箱系统；不需要自建；
> 2.正常发送邮件需要配置定时计划，请仔细看wiki说明



> 1.发送邮件用的smtp模式，也就是使用第三方邮箱系统；不需要自建；
> 2.正常发送邮件需要配置定时计划，请仔细看wiki说明

好的，谢谢，计划任务我加了，看来是计划任务不知道哪里出错了
