### ISSUE TITLE
支付宝当面付不生成二维码

### ISSUE THREAD

**Issue by Insightfy** [zlkbdotnet/zfaka#34]
可以自动跳转到支付宝 也可以点击跳转支付。但是无法正常生成二维码，导致电脑用户无法正常支付。
https://github.com/zlkbdotnet/zfaka/blob/master/public/res/images/pay/weburl-error.png
这个图看的心态都被崩了哈哈。
还是谢谢大佬无私奉献做出这么好的项目，话说想试试收款宝在哪里可以申请？

**Comment by zlkbdotnet** [comment]
请参考：https://github.com/zlkbdotnet/zfaka/wiki/%E7%B3%BB%E7%BB%9F%E9%85%8D%E7%BD%AE%E6%8C%87%E5%8D%97
进行weburl配置

**Comment by zlkbdotnet** [comment]
收款宝属于收费服务，请加群746883479
