### ISSUE TITLE
小白求教个问题

### ISSUE THREAD

**Issue by 1404939641** [zlkbdotnet/zfaka#39]
我用的码支付里的支付宝支付，用挂机宝把码支付的那个程序运行起来，但是每次支付好那个程序应该发送异步通知是总是会失败，我用宝塔建的站。防跨站攻击保护已经关了

**Comment by zlkbdotnet** [comment]
码支付那边要配置通知地址

**Comment by 1404939641** [comment]
http://域名/product/notify/?paymethod=codepayalipay。是这种格式刷吗？

**Comment by zlkbdotnet** [comment]
你去zfaka后台，支付接口处，有显示异步通知地址；

当然，前提你得先去zfaka后台，把weburl给修改正确；

最好仔细看wiki文档
