### ISSUE TITLE
支付点击二维码自动跳转功能

### ISSUE THREAD

**Issue by Insightfy** [zlkbdotnet/zfaka#4]
码支付官方的demo支持点击二维码直接跳转.能加入一下？
现在基本都是手机操作，得先截图，然后扫一扫打开相册，然后支付删截图....

**Comment by JesonWang09** [comment]
> 码支付官方的demo支持点击二维码直接跳转.能加入一下？
> 现在基本都是手机操作，得先截图，然后扫一扫打开相册，然后支付删截图....

你直接把按钮换成二维码对应的链接，手机上直接就跳转了啊

**Comment by zlkbdotnet** [comment]
刚特地下载了最新的码支付DEMO，并在线测试了他的功能与页面；发现最新的码支付居然用上了socket，真实支付宝地址，需要3－4次socket请求才能获取；不知道作者是基于什么样的考虑；由于我只是使用纯粹的API接口进行支付对接，所以无法完全使用这个功能。SO，我放弃对码支付这个功能的支持。如果你们对这个功能有需求，可以去向码支付服务商请求，让他在创建订单时把支付宝链接同时返回回来即可；
