### ISSUE TITLE
建议添加商户版微信+支付宝h5支付

### ISSUE THREAD

**Issue by mcwenzai** [zlkbdotnet/zfaka#42]
那样就可以不用截图扫码，输入金额去支付了。就可以自动唤起微信、支付宝app，直接支付。而且不需要弄码支付那样麻烦的东西。

**Comment by Insightfy** [comment]
门槛太高了 很多人搞不到账户的
与其小众使用，不如你直接找作者py吧

**Comment by mcwenzai** [comment]
扫码支付很麻烦，而且对接码支付特别麻烦，经常出问题，总是提示“商户收款存在异常“”

**Comment by mcwenzai** [comment]
软件还要24小时挂机，微信每隔24小时还要授权，而且延迟很高。

**Comment by Insightfy** [comment]
第一 我亲测可以跳转到支付宝微信。第二存在异常是你被检测 不是zfaka造成。
第三 软件24小时挂机只需要一个学生机解决。 没有你说的24小时授权 延迟就30s
而且你所说的支付方式9成一样的使用者无法实现，也就是说这是你的个人需求，没理由为了你一个人去适配。
最后在重申一遍 我不是作者。作者说过这类东西他不负责对接，你可以付费去找作者PY。
如果你觉得麻烦可以使用作者的收款宝。

**Comment by mcwenzai** [comment]
30秒的延迟+24小时挂机，这还不够麻烦吗？还要手动扫码支付，动不动就付款失败。

**Comment by zlkbdotnet** [comment]
1.企业支付宝,已经对接了，可以自动调转，并调起支付宝客户端
2.企业微信，这块我很受伤了，具体原因不详说了，群友都知道；最后一次测试时，是可以了，但奇葩的是付款了，钱不到账；

总之，有缘再弄

**Comment by pxw2002** [comment]
https://www.dedemao.com/wx/demo.html

**Comment by zlkbdotnet** [comment]
商户版微信,已经于1.4.0版本上测试可用了
