### ISSUE TITLE
安装问题

### ISSUE THREAD

**Issue by yaoqh2010** [zlkbdotnet/zfaka#43]

**Comment by kongjiaohou** [comment]
重新做一遍: PHP设置 - 安装插件 - PATH_INFO关闭 - 重启PHP。

这是宝塔5.X，6.X的设置方法你自己找找。

**Comment by SpiralG** [comment]
重新做一遍: PHP设置 - 安装插件 - PATH_INFO关闭 - 重启PHP。

这是宝塔5.X，6.X的设置方法你自己找找。

**Comment by yaoqh2010** [comment]
还是没搞定。。。。我是6.x，无语😳
