### ISSUE TITLE
宝塔安装yaf问题

### ISSUE THREAD

**Issue by ggoog** [zlkbdotnet/zfaka#44]
按照文档安装，
不知道这个配置要添加到哪里
yaf.use_namespace=1
<img width="776" alt="image" src="https://user-images.githubusercontent.com/25149246/54402828-8baa1200-4708-11e9-9843-4f99d2aada25.png">
安装yaf之后，配置文件搜不到yaf
<img width="604" alt="image" src="https://user-images.githubusercontent.com/25149246/54402874-c613af00-4708-11e9-827c-6a2b8b8516dd.png">

**Comment by dejavui** [comment]
复制粘贴
