### ISSUE TITLE
除了收款宝，其余一个支付接口都用不了，也有可能是我不会用吧

### ISSUE THREAD

**Issue by mcwenzai** [zlkbdotnet/zfaka#47]
微信支付确定不行，其余的不知道是配置错误，还是什么原因，都不行。

**Comment by zlkbdotnet** [comment]
呵呵

我可以很大声的告诉你，就是你不会用．

**Comment by qq24021438** [comment]
> 微信支付确定不行，其余的不知道是配置错误，还是什么原因，都不行。

其实我告诉你就是不能用，他想变相的去收费，如果有这么问的就闲我们不会用，
有意的加了很多坑。
