### ISSUE TITLE
邮箱系统有点混乱

### ISSUE THREAD

**Issue by Insightfy** [zlkbdotnet/zfaka#5]
作者你好 东西非常好，逻辑也很棒，有一点小意见。
ui改成md风格会更讨喜一些。
邮箱系统 发件人邮箱和邮箱地址这两个不知道写什么
我用的是sendgrid，给的参数有
smtp_host 服务商的发件地址
smtp_username  服务商用户名
smtp_port 端口465
smtp_name 发件邮箱地址
smtp_sender 发件人昵称
smtp_passsword 密码
同样是6项但是有上面提的两项比知道写在哪里 麻烦了

**Comment by zlkbdotnet** [comment]
大部分邮件系统都是大同小异，

邮箱地址  基本等同于发件人地址，也叫邮箱账户，或者邮箱用户名

发件人邮箱 就是客户收信时显示的发件人邮箱

目前我提供的参数几乎可以包含大部分邮箱系统设置。当然，如果有非常特别的邮件系统除外，那我也无能为力
