### ISSUE TITLE
有赞支付设置好了 报：支付接口请求失败

### ISSUE THREAD

**Issue by shijingyu** [zlkbdotnet/zfaka#54]
您好 请教一下：
有赞支付设置好了： appid和sercet 和店铺id
推送网址设置的 ：http://我的域名/product/notify/?paymethod=yzpay 

报：支付接口请求失败
在log文件夹没找到日志，请问日志在哪里， 从哪里排错

**Comment by qq810864453** [comment]
www.iekeji.cn/zdyk/206.html   这个是有赞对接教程

**Comment by zlkbdotnet** [comment]
很多有赞已经无法使用
