### ISSUE TITLE
关于Zfaka程序对接支付接口 不成功返回问题

### ISSUE THREAD

**Issue by qq810864453** [zlkbdotnet/zfaka#55]
关于Zfaka程序对接支付接口 不成功返回问题

我对接的是支付宝web接口  和  有赞接口   + 支付宝面对面

我成功支付后   不返回成功支付和卡密  显示待支付状态   两个都测试了都是显示待支付状态

好多坑，求大神带一下。

图片地址
 https://attach.52pojie.cn/forum/201903/31/175803jimdiiiihirmpqfp.png

**Comment by zlkbdotnet** [comment]
自己问题,自己处理

**Comment by qq810864453** [comment]
什么问题呢，该如何处理呢
