### ISSUE TITLE
有一个bug,下单输入订单数量时无法清零

### ISSUE THREAD

**Issue by yunxinlxsy** [zlkbdotnet/zfaka#62]
在下单界面填入购买数量时,无法删除到0,他会直接变成库存的数量
例如:库存是56,我需要买3件,但是这个bug它无法直接删除到0以便我输入3,删除时它会直接变成56.它只能用鼠标左键选中方框内数字,然后重新输入新的数字覆盖掉旧的数字,不知道是这样设计的还是什么原因,其他人很多网站也是这样,但是这样真的很不方便.
例如http://fk.xpsss.com/

**Comment by yunxinlxsy** [comment]
虽然有点击按钮用于增加或者减少数量,但是很少会去用点击的方式,而且移动网页端也看不见那个用于改变数量的箭头

**Comment by abcd171422** [comment]
不适用于移动端。，

**Comment by zlkbdotnet** [comment]
这个bug已经在开发版中修复了，请手工下载 zfaka/public/res/mods/product.js

**Comment by yunxinlxsy** [comment]
多谢，已经解决了，给你个赞
