### ISSUE TITLE
发卡后不能减库存

### ISSUE THREAD

**Issue by hyjsos123** [zlkbdotnet/zfaka#8]
实际应用了一把，。发现每次购买完商品后。不能自动去掉已发出的卡密。当再次购买时，仍然为上次已发出的卡密。这是我的发卡地址。faka.xsos.top    有个商品我调整为0.01了。大佬可以实际买买测试下。

**Comment by zlkbdotnet** [comment]
后台商品管理处，把商品改为限制库存即可

商品管理处有说明，请仔细看
