### ISSUE TITLE
关于折扣计算问题

### ISSUE THREAD

**Issue by Pakne** [zlkbdotnet/zfaka#80]
我设置了购买数量达到10的时候折扣0.7、20的时候0.6、30的时候0.5、100的时候0.4
但是从购买数量2开始就有折扣了
而且购买数量9和11比数量10便宜
![数量二](https://user-images.githubusercontent.com/44231215/57137559-ca904600-6de2-11e9-9bda-7bbf383cac72.png)
![数量9](https://user-images.githubusercontent.com/44231215/57137560-cb28dc80-6de2-11e9-8677-9bfc969a0031.png)
![数量10](https://user-images.githubusercontent.com/44231215/57137562-cb28dc80-6de2-11e9-8b51-f8ed49534adc.png)
![数量11](https://user-images.githubusercontent.com/44231215/57137564-cbc17300-6de2-11e9-91dd-f4e245dc455b.png)
![批发折扣](https://user-images.githubusercontent.com/44231215/57137565-cbc17300-6de2-11e9-8ce8-45a8691c1ab0.png)
![1元](https://user-images.githubusercontent.com/44231215/57137566-cc5a0980-6de2-11e9-8402-625f81aac0fc.png)

**Comment by zlkbdotnet** [comment]
已经修复
