### ISSUE TITLE
网站登陆验证不显示，出现的是破裂图片

### ISSUE THREAD

**Issue by ray-lmxcjjcl** [zlkbdotnet/zfaka#81]
安装后是正常的，都测试成功，过几天打开网站，登陆发现验证码无法显示，无法登陆后台了，期间服务器没有动过，请教解决方法，谢谢

**Comment by zlkbdotnet** [comment]
1.请检查网络是否正常，网站太慢有时会这样；
2.请检查环境是否出现问题，可以查看程序根目录下logs文件夹
3.你可以去数据库打开t_config，修改配置名为yzmswitch的value值为0，然后去手工清除程序根目录下temp文件夹里的所有文件，再找开后台，就不需要验证码了

**Comment by ray-lmxcjjcl** [comment]
> 1.请检查网络是否正常，网站太慢有时会这样；
> 2.请检查环境是否出现问题，可以查看程序根目录下logs文件夹
> 3.你可以去数据库打开t_config，修改配置名为yzmswitch的value值为0，然后去手工清除程序根目录下temp文件夹里的所有文件，再找开后台，就不需要验证码了

你好，这边尝试了，失败
1.这边多次测试网络和vps都是正常的，
2.longs不太懂怎么看
3.已经按你的要求把yzmswitch的value值改为0，temp文件夹里的所有文件也删除了，但是打开后台依旧要输入验证码，这边没有使用cdn,也尝试换浏览器和无痕模式，应该没有缓存导致未生效的问题，还是不行

**Comment by zlkbdotnet** [comment]
哦，我记错了，是t_config，修改配置名为adminyzmswitch的value值为0 然后去手工清除程序根目录下temp文件夹里的所有文件，再找开后台，就不需要验证码了

**Comment by zlkbdotnet** [comment]
至于为什么二维码如果生成，唯一的解释就是你的环境有问题；

如果你不信，我只能说见鬼了

**Comment by ray-lmxcjjcl** [comment]
嗯，按你的要求已把验证码成功关闭了，感谢，已可以正常登陆，至于环境问题我也不懂，当时搭建好时那两天都是正常输入验证码登陆ok的，vps也没动过，昨天去登陆才发现验证码破裂
