### ISSUE TITLE
码支付——订单支付问题

### ISSUE THREAD

**Issue by ZengX2017** [zlkbdotnet/zfaka#89]
### 这个问题实在困扰了很久，搭建完成之后测试订单支付时会直接弹出如下的二维码，不像演示地址那样先弹出一个窗口后再自动跳转。
![image](https://user-images.githubusercontent.com/29659882/58366015-de6d2a80-7efe-11e9-8003-db29bdf9e370.png)

### 在码支付这里可以看到订单，即使是支付了也还是待支付，直至超时支付失败。
![image](https://user-images.githubusercontent.com/29659882/58366065-63f0da80-7eff-11e9-9d21-eca09061bbfd.png)

### 如果作者能指点迷津的话实在是感激不尽，谢谢

**Comment by zlkbdotnet** [comment]
１.为什么不象演示站那样，跳转？　因为我的演示站用的不是码支付；
２.码支付问题，建议你去找码支付
